version: '3'

services:

  acquire:
    restart: always
    build:
      context: .
      dockerfile: ./build/acquire/Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    command:
      python3 /app/acquire.py

  # based on https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
  # official docs at https://hub.docker.com/_/mongo

  # https://faun.pub/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: nycbuswatcher
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - ./build/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro #bug may be unnecessary for authentication but useful for creating an index?


  api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - db:/app/data


volumes:
  traefik-public-certificates:
  db:
